stages:
  - update
  - test
  - build
  - push
  - deploy
  - newrelic
  - docs

before_script:
  - make clean

after_script:
  - make clean

update:
  stage: update
  script:
    - make install

test:
  stage: test
  script:
    - make test
  coverage: '/^TOTAL.*\s([0-9]+\%)$/'

build:
  stage: build
  script:
    - make docker VERSION=$CI_COMMIT_SHA BRANCH=$CI_COMMIT_REF_NAME

push:
  stage: push
  script:
    - make push VERSION=$CI_COMMIT_SHA BRANCH=$CI_COMMIT_REF_NAME

elasticbeanstalk-dev:
  stage: deploy
  only:
    - develop
  script:
    - make deploy-dev VERSION=$CI_COMMIT_SHA BRANCH=$CI_COMMIT_REF_NAME
  environment:
    name: development
    url: http://stt-dev-zenon-salesforce-worker-a.us-east-1.elasticbeanstalk.com

elasticbeanstalk-preprod:
  stage: deploy
  only:
    - preprod
  script:
    - make deploy-preprod VERSION=$CI_COMMIT_SHA BRANCH=$CI_COMMIT_REF_NAME
  environment:
    name: preprod
    url: https://stt-preprod-zenon-salesforce-worker-a.us-east-1.elasticbeanstalk.com

elasticbeanstalk-prod:
  stage: deploy
  only:
    - master
  script:
    - make deploy-prod VERSION=$CI_COMMIT_SHA BRANCH=$CI_COMMIT_REF_NAME
  environment:
    name: production
    url: https://stt-prod-zenon-salesforce-worker-a.us-east-1.elasticbeanstalk.com

newrelic:
  stage: newrelic
  only:
    - master
  script:
    - make newrelic NR_APP_ID=$NEW_RELIC_APP_ID_PROD NR_API_KEY=$NEW_RELIC_API_KEY VERSION=$CI_COMMIT_SHA USER_EMAIL=$GITLAB_USER_EMAIL

publish-docs-dev:
  stage: docs
  only:
    - develop
  script:
    - make clean-docs
    - make docs VERSION=$CI_COMMIT_SHA
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEV && export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV && export AWS_DEFAULT_REGION=us-east-1
    - make publish-docs DOCS-BUCKET=stt-dev-api-docs
    - make clean-docs
  environment:
    name: development-docs
    url: https://s3.amazonaws.com/stt-dev-api-docs/invoice/index.html
  allow_failure: true

publish-docs-preprod:
  stage: docs
  only:
    - preprod
  script:
    - make clean-docs
    - make docs VERSION=$CI_COMMIT_SHA
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PRE_PROD && export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PRE_PROD && export AWS_DEFAULT_REGION=us-east-1
    - make publish-docs DOCS-BUCKET=stt-preprod-api-docs
    - make clean-docs
  environment:
    name: preprod-docs
    url: https://s3.amazonaws.com/stt-preprod-api-docs/invoice/index.html
  allow_failure: true

publish-docs:
  stage: docs
  only:
    - master
  script:
    - make clean-docs
    - make docs VERSION=$CI_COMMIT_SHA
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PROD && export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PROD && export AWS_DEFAULT_REGION=us-east-1
    - make publish-docs
    - make clean-docs
  environment:
    name: production-docs
    url: https://s3.amazonaws.com/stt-prod-api-docs/invoice/index.html
  allow_failure: true
