version: '3.7'

services:
  test:
    build: 
      dockerfile: resources/Dockerfile
      context: ../
    ports:
      - 5000:5000
    environment:
      PYTHONPATH: /usr/src/app/src:/usr/src/app/tests
    volumes:
      - ..:/usr/src/app
    command: coverage run --source=src --branch -m unittest discover -s tests -p "test_*.py"