version: '2.1'

networks:
  ztech-elk:
    external:
      name: ztech-elk_ztech-elk

services:
  app:
    build: 
      dockerfile: resources/Dockerfile
      context: ../
    environment:
      WEB_CONCURRENCY: 2
      LOGSTASH: logstash
      ELASTICSEARCH: elasticsearch
      APP_NAME: ztech
    ports:
      - 5000:5000
    networks: 
      - ztech-elk
    volumes:
      - ..:/usr/src/app

